"""
scripts/run_analysis.py
=======================
Core analysis script shared by the GitHub Action and the local test runner.

Usage
-----
  # From the GitHub Action (reads file list from --files):
  python scripts/run_analysis.py --files changed_files.txt

  # Explicit file list:
  python scripts/run_analysis.py src/foo.py src/bar.py

  # Read from stdin (pipe):
  git diff --name-only HEAD~1 | grep '.py$' | python scripts/run_analysis.py --stdin

Outputs
-------
  analysis_comment.md   — Markdown table ready to POST as a PR comment
  stdout                — same table printed for CI logs / local use
"""

import ast
import argparse
import sys
import os
import textwrap
from datetime import datetime, timezone
from pathlib import Path

import requests

API_BASE    = os.getenv("GRAPHAULT_API", "http://localhost:8000")
THRESHOLD   = 0.5417
OUTPUT_FILE = os.getenv("ANALYSIS_OUTPUT", "analysis_comment.md")
TIMEOUT     = 10   # seconds per /predict call


# ── Function extraction ───────────────────────────────────────────────────────

def extract_functions(filepath: str) -> list[tuple[str, str, int]]:
    """Return [(func_name, source_code, start_line), ...] for every function in the file."""
    try:
        source = Path(filepath).read_text(encoding="utf-8", errors="replace")
        tree   = ast.parse(source)
    except (SyntaxError, OSError, ValueError):
        return []

    lines   = source.splitlines()
    results = []
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            start   = node.lineno - 1
            end     = node.end_lineno
            snippet = "\n".join(lines[start:end])
            results.append((node.name, snippet, node.lineno))
    return results


# ── API call ──────────────────────────────────────────────────────────────────

def predict(code: str) -> dict | None:
    """POST to /predict; return response dict or None on error."""
    try:
        resp = requests.post(
            f"{API_BASE}/predict",
            json={"code": code},
            timeout=TIMEOUT,
        )
        if resp.status_code == 200:
            return resp.json()
        return {"error": f"HTTP {resp.status_code}"}
    except requests.RequestException as e:
        return {"error": str(e)}


# ── Markdown formatting ───────────────────────────────────────────────────────

def _status_icon(score: float) -> str:
    if score >= THRESHOLD:
        return "🚨 FLAGGED"
    if score >= THRESHOLD * 0.6:
        return "⚠️ REVIEW"
    return "✅ LOW RISK"


def build_comment(rows: list[dict], changed_files: list[str]) -> str:
    """
    rows: [{"file", "func", "line", "score", "nodes", "error"}, ...]
    """
    now    = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    ok     = [r for r in rows if "error" not in r]
    errors = [r for r in rows if "error" in r]

    flagged = sum(1 for r in ok if r["score"] >= THRESHOLD)
    review  = sum(1 for r in ok if THRESHOLD * 0.6 <= r["score"] < THRESHOLD)
    clean   = len(ok) - flagged - review

    lines = [
        "## Graphault Risk Analysis",
        "",
        f"Scanned **{len(ok)} function{'s' if len(ok) != 1 else ''}** "
        f"across **{len(changed_files)} changed Python file{'s' if len(changed_files) != 1 else ''}**.",
        "",
    ]

    if ok:
        lines += [
            "| File | Function | Line | Score | Status |",
            "|------|----------|-----:|-----:|--------|",
        ]
        # Flagged first, then by score descending
        for r in sorted(ok, key=lambda x: -x["score"]):
            score_fmt = f"`{r['score']:.4f}`"
            lines.append(
                f"| `{r['file']}` | `{r['func']}` | {r['line']} "
                f"| {score_fmt} | {_status_icon(r['score'])} |"
            )
        lines.append("")

    if errors:
        lines += [
            "<details><summary>Parse / API errors</summary>",
            "",
            "| File | Function | Error |",
            "|------|----------|-------|",
        ]
        for r in errors:
            lines.append(f"| `{r['file']}` | `{r['func']}` | {r['error']} |")
        lines += ["", "</details>", ""]

    summary_parts = []
    if flagged: summary_parts.append(f"**{flagged} flagged**")
    if review:  summary_parts.append(f"{review} to review")
    if clean:   summary_parts.append(f"{clean} clean")
    summary = " · ".join(summary_parts) if summary_parts else "nothing to report"

    lines += [
        f"**{summary}** &nbsp;·&nbsp; "
        f"Threshold `{THRESHOLD}` &nbsp;·&nbsp; "
        f"Model: GNN AST graph classifier",
        "",
        "> ℹ️ **Advisory only — this comment never blocks a merge.**  ",
        f"> Generated by [Graphault](https://github.com/jayeshmehra344/codesense) at {now}.",
    ]

    return "\n".join(lines)


# ── Main ──────────────────────────────────────────────────────────────────────

def run(file_paths: list[str]) -> str:
    """Analyse all functions in file_paths; return the markdown comment."""
    file_paths = [f for f in file_paths if f and Path(f).exists()]
    if not file_paths:
        return "## Graphault Risk Analysis\n\nNo changed Python files found."

    print(f"Graphault: analysing {len(file_paths)} file(s) via {API_BASE}/predict")

    rows = []
    for filepath in file_paths:
        funcs = extract_functions(filepath)
        if not funcs:
            print(f"  {filepath}: no functions found or parse error")
            continue
        print(f"  {filepath}: {len(funcs)} function(s)")
        for name, code, lineno in funcs:
            result = predict(code)
            if result is None or "error" in result:
                rows.append({
                    "file": filepath, "func": name, "line": lineno,
                    "error": result.get("error", "no response") if result else "timeout",
                })
            else:
                rows.append({
                    "file": filepath,
                    "func": name,
                    "line": lineno,
                    "score": result["risk_score"],
                    "nodes": result["num_nodes"],
                })
            if "score" in rows[-1]:
                s = rows[-1]["score"]
                tag = "FLAGGED" if s >= THRESHOLD else ("REVIEW" if s >= THRESHOLD * 0.6 else "ok")
                print(f"    {name}:{lineno}  {s:.4f}  {tag}")
            else:
                print(f"    {name}:{lineno}  ERROR: {rows[-1].get('error', '')}")

    return build_comment(rows, file_paths)


def main():
    parser = argparse.ArgumentParser(description="Graphault function risk analyser")
    parser.add_argument("files", nargs="*", help="Python files to analyse")
    parser.add_argument("--files", dest="files_arg",
                        help="Path to a text file listing one Python file per line")
    parser.add_argument("--stdin", action="store_true",
                        help="Read file list from stdin")
    args = parser.parse_args()

    if args.stdin:
        file_paths = [l.strip() for l in sys.stdin if l.strip()]
    elif args.files_arg:
        file_paths = Path(args.files_arg).read_text().splitlines()
        file_paths = [f.strip() for f in file_paths if f.strip()]
    else:
        file_paths = args.files

    comment = run(file_paths)

    Path(OUTPUT_FILE).write_text(comment, encoding="utf-8")
    print(f"\n--- PR comment written to {OUTPUT_FILE} ---\n")
    print(comment)


if __name__ == "__main__":
    main()
